### ISSUE TITLE
Please remove shebang from __main__.py

### ISSUE THREAD

**Issue by hegjon** [thombashi/tcolorpy#2]
Please remove shebang from [__main__.py](https://github.com/thombashi/tcolorpy/blob/master/tcolorpy/__main__.py). It makes no sense there:

 - the file is not executable, hence the shebang does nothing
 - even if it was executable, nobody executes this by going to terminal and running the file, it is a Python module
 - the purpose of this file is to allow executing `python -m tcolorpy` which does not require a shebang

for details see https://bugzilla.redhat.com/show_bug.cgi?id=2058411#c8

**Comment by thombashi** [comment]
Fixed by #3
